name: CI-CD CodeArtifact (Node + Snyk)

on:
  push:
    branches: [ "main" ]

jobs:
  build-scan-publish:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Resolve CodeArtifact npm endpoint & token
        shell: powershell
        run: |
          $ErrorActionPreference = "Stop"
          $env:CODEARTIFACT_AUTH_TOKEN = (aws codeartifact get-authorization-token --domain secure-domain --domain-owner 626635402082 --query authorizationToken --output text)
          $env:CODEARTIFACT_NPM_ENDPOINT = (aws codeartifact get-repository-endpoint --domain secure-domain --domain-owner 626635402082 --repository dev-repo --format npm --query repositoryEndpoint --output text)
          echo "CODEARTIFACT_AUTH_TOKEN=$env:CODEARTIFACT_AUTH_TOKEN" >> $env:GITHUB_ENV
          echo "CODEARTIFACT_NPM_ENDPOINT=$env:CODEARTIFACT_NPM_ENDPOINT" >> $env:GITHUB_ENV

      - name: Configure npm to CodeArtifact
        shell: powershell
        run: |
          npm set registry $env:CODEARTIFACT_NPM_ENDPOINT
          npm set //$(($env:CODEARTIFACT_NPM_ENDPOINT -replace '^https?:','')):always-auth=true
          npm set //$(($env:CODEARTIFACT_NPM_ENDPOINT -replace '^https?:','')):_authToken=$env:CODEARTIFACT_AUTH_TOKEN

      - name: Install deps
        run: npm install

      - name: Install Snyk CLI (cross‑platform)
        uses: snyk/actions/setup@master

      - name: Run Snyk scan
        run: snyk test --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Publish to CodeArtifact
        shell: powershell
        run: npm publish
