name: Docker Build & Push (ECR Enhanced)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docker:
    runs-on: [self-hosted, Windows, X64]
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REPO: myapp

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Ensure ECR repo exists
        run: |
          set -e
          aws ecr describe-repositories --repository-names $ECR_REPO >/dev/null 2>&1 ||           aws ecr create-repository --repository-name $ECR_REPO --image-scanning-configuration scanOnPush=true

      - name: Login to ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push
        run: |
          set -e
          REGISTRY=${{ steps.ecr.outputs.registry }}
          IMAGE=$REGISTRY/$ECR_REPO:latest
          docker build -t $IMAGE .
          docker push $IMAGE
